version: "3.9"
services:
  mysql:
    image: mysql:8.2.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: Queue_Information
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined